### ISSUE TITLE
customScriptExtension resource: add parameter to control the file name of the downloaded resource

### ISSUE THREAD

**Issue by ivansharamok** [Azure/azure-resource-manager-schemas#1052]
## Problem

If the file URI format doesn't follow what is provided in [CustomScriptExtension documentation](https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/custom-script-windows#property-values), then the extension fails to download the file or can fail to execute downloaded script using anticipated script name.
For instance, if I configure the `CustomScriptExtension` to download a file from a private repo hosted in Gitlab, the file download fails. To download raw file content from Gitlab private repo, the URI format should follow this pattern `https://gitlab.com/api/v4/projects/${PROJECT_ID}/repository/files/${URI_ENCODED_PATH}/raw?ref=master&private_token=${ACCESS_TOKEN}`.
For instance:

```bash
PROJECT_ID=13
# file path must be in URI-encoded format (i.e. '/' -> '%2F', etc.)
URI_ENCODED_PATH='path%2Fto%2Ffile%2Fconfigure-win-node.ps1'
# if repo is private, use PAT to access resources
ACCESS_TOKEN='xxxxxxxx'
# Gitlab URI formate to fetch file content
https://gitlab.com/api/v4/projects/${PROJECT_ID}/repository/files/${URI_ENCODED_PATH}/raw?ref=master&private_token=${ACCESS_TOKEN}
```

`CustomScriptExtension` configuration:

```json
  [REDUCTED]
  "variables": {
    "resourceUri": "[concat(uri(parameters('_artifactsLocation'), uriComponent(trim(parameters('_artifactsFilePath')))), '/raw', '?ref=', parameters('gitBranchName'))]",
    "resourceUriWithToken": "[concat(variables('resourceUri'), '&', 'private_token=', parameters('_artifactsAccessToken'))]",
  },
  "resources": [
    [REDUCTED]
    {
      "type": "Microsoft.Compute/virtualMachines/extensions",
      "name": "[concat(variables('vmName'),'-win', copyindex(), '/installcustomscript')]",
      "apiVersion": "2018-06-01",
      "location": "[parameters('location')]",
      "copy": {
        "name": "windowsCount",
        "count": "[parameters('numberOfVMs')]"
      },
      "dependsOn": [
        "[concat('Microsoft.Compute/virtualMachines/', variables('vmName'), '-win', copyindex())]"
      ],
      "properties": {
        "publisher": "Microsoft.Compute",
        "type": "CustomScriptExtension",
        "typeHandlerVersion": "1.10",
        "autoUpgradeMinorVersion": true,
        "protectedSettings": {},
        "settings": {
          "fileUris": [
            "[if(not(equals(parameters('_artifactsAccessToken'), '')), variables('resourceUriWithToken'), variables('resourceUri'))]"
          ],
          "commandToExecute": "powershell.exe -ExecutionPolicy Unrestricted -File configure-win-node.ps1"
        }
      }
    }
  ]
```

Once VM gets provisioned and the deployment starts executing the extension, it fails with the following error (the stack trace retrieved from `C:\WindowsAzure\Logs\Plugins\Microsoft.Compute.CustomScriptExtension\1.*\CustomScriptHandler.log`):

```
[3280+00000001] [07/10/2020 04:27:02.17] [INFO] HandlerSettings = ProtectedSettingsCertThumbprint: 5818102F49DDCA4DDC53367CABB5CDB0DB0AD0F8, ProtectedSettings: {MIIBsAYJKoZIhvcNAQcD[REDUCTED]}, PublicSettings: {FileUris: [https://gitlab.com/api/v4/projects/13/repository/files/path%2Fto%2Ffile%2Fconfigure-win-node.ps1/raw?[REDACTED]], CommandToExecute: powershell.exe -ExecutionPolicy Unrestricted -File configure-win-node.ps1}
[3280+00000001] [07/10/2020 04:27:02.41] [INFO] Downloading files specified in configuration...
[3280+00000001] [07/10/2020 04:27:02.53] [INFO] DownloadFiles: fileDownloadPath = C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.10.9\Downloads\0
[3280+00000001] [07/10/2020 04:27:02.53] [INFO] WebClientDownloader: starting download fileUri = https://gitlab.com/api/v4/projects/13/repository/files/path%2Fto%2Ffile%2Fconfigure-win-node.ps1/raw?[REDACTED]
[3280+00000001] [07/10/2020 04:27:02.80] [WARN] WebClient: non retryable error occurred System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at Microsoft.WindowsAzure.GuestAgent.Plugins.MsiUtils.WebClientWithRetryAbstract.ActionWithRetries(Action action)
[3280+00000001] [07/10/2020 04:27:02.81] [FATAL] Failed to download all specified files. Exiting. Exception: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at Microsoft.WindowsAzure.GuestAgent.Plugins.MsiUtils.WebClientWithRetryAbstract.ActionWithRetries(Action action)
   at Microsoft.WindowsAzure.GuestAgent.Plugins.CustomScriptHandler.Downloader.WebClientDownloader.Download(Uri fileUri, String uriStringForLog, String downloadDir, Msi msi)
   at Microsoft.WindowsAzure.GuestAgent.Plugins.CustomScriptHandler.Downloader.DownloadManager.DownloadWithWebClientDownloader(IDictionary`2 uriForDownloadAndLogging, String downloadDir, Msi msi)
   at Microsoft.WindowsAzure.GuestAgent.Plugins.CustomScriptHandler.Downloader.DownloadManager.DownloadFiles(IList`1 fileUriStrs, ProtectedSettings protectedSettings, String downloadDir, Boolean isFileUrisProtected)
   at Microsoft.WindowsAzure.GuestAgent.Plugins.CustomScriptHandler.Program.Main(String[] args)
[3280+00000001] [07/10/2020 04:27:02.83] [INFO] {"sequenceNumber":0,"totalDuration":1154,"status":"error","code":1,"filesDownloaded":0,"durationOfFileDownload":318,"statusFileAccessed":2,"operation":"enable","operationDuration":86,"operationResult":"success","operationSizeOfOutput":0,"operationSizeOfError":0}

```

To work around the download issue, one can use `blod-id` of Gitlab file instead of the `filePath`. In this case the file URI should follow this pattern `https://gitlab.com/api/v4/projects/7546518/repository/blobs/${BLOB_ID}/raw?ref=master&&private_token=${ACCESS_TOKEN}`.

However, in this case the file content is saved into `C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.10.9\Downloads\0\raw` file and real file name gets lost. Moreover, since the new file name doesn't have `.ps1` extension, it can't be invoked as a `Powershell` script without additional tricks.

## Workaround

Specifically, for Gitlab example one can use `BLOB_ID` to get the file content and then use `Invoke-Command` to retrieve and execute the script saved into `.\raw` file.

Example to download the file

```bash
PROJECT_ID=13
# file path must be in URI-encoded format (i.e. '/' -> '%2F', etc.)
URI_ENCODED_PATH='path%2Fto%2Ffile%2Fconfigure-win-node.ps1'
# if repo is private, use PAT to access resources
ACCESS_TOKEN='xxxxxxxx'
GITLAB_PROJECT_BLOB_URI='https://gitlab.com/api/v4/projects/${PROJECT_ID}/repository/blobs/'
# when using Blob ID, the ACCESS_TOKEN must include read_api permission
BLOB_ID=$(curl -s --head -H "Private-Token: ${ACCESS_TOKEN}" "https://gitlab.com/api/v4/projects/7546518/repository/files/${URI_ENCODED_PATH}/raw?ref=master" | grep 'x-gitlab-blob-id' | cut -d ' ' -f2)
```

In this case the `fileUri` provided to the `CustomScriptExtension` definition would look like this `https://gitlab.com/api/v4/projects/${PROJECT_ID}/repository/blobs/${BLOB_ID}/raw?ref=master&private_token=${ACCESS_TOKEN}`.

Example to execute the `PS` script on Windows VM when script content is saved into file with name `raw`:

```json
    [REDUCTED]
      "properties": {
        "publisher": "Microsoft.Compute",
        "type": "CustomScriptExtension",
        "typeHandlerVersion": "1.10",
        "autoUpgradeMinorVersion": true,
        "protectedSettings": {},
        "settings": {
          "fileUris": [
            "[if(not(equals(parameters('_artifactsAccessToken'), '')), variables('resourceUriWithToken'), variables('resourceUri'))]"
          ],
          "commandToExecute": "powershell.exe -Command \"Invoke-Command -ScriptBlock ([ScriptBlock]::Create((Get-Content raw -Raw)))\""
        }
      }
    [REDUCTED]
```

## Expected behavior

The extension should offer enough controls to save the file from any URI that serves the raw file content into a file with expected name.
One way to achieve this could be to provide a parameter for `CustomScriptExtension` that allows user to choose the file name(s) for the content(s) downloaded from the `fileUris`. Or have the parameter to specify the HTTP header name from which the file name can be retrieved. For instance, Gitlab uses `x-gitlab-file-name` HTTP response header to provide the file name for the retrieved raw content.

**Comment by Drewm3** [comment]
This is a feature request, and not a schema issue. The issue in this repro should be closed, and instead the request should be opened in the upcoming UserVoice replacement.

**Comment by anthony-c-martin** [comment]
Closing as per @Drewm3's comment.
